### ISSUE TITLE
CPU code returns 0.5 for all videos with warning message

### ISSUE THREAD

**Issue by P-Light** [deepware/deepfake-scanner#5]
CUDA code retuns more realistic values without any warnings.

Maybe
```python
252 except Exception as e:
253    print(e, file, file=sys.stderr)
254    return 0.5
```
should be changed.

**Comment by P-Light** [comment]
`Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same data/mqzvfufzoq.mp4`

Something wrong with CPU ver.

**Comment by dodobyte** [comment]
can you verify the fix? thanks for the feedback.

**Comment by P-Light** [comment]
It was very quick fix, perfect! Now both CPU and CUDA works same. Thanks!
Maybe it would be better if error message will contains "error" word :)

**Comment by dodobyte** [comment]
Error messages will be updated soon. thanks.
