### ISSUE TITLE
Threshold to determine a video as fake?

### ISSUE THREAD

**Issue by reobroqn** [deepware/deepfake-scanner#7]
Hi! 
I use the scanner on deepware.ai to scan a few videos and the result is fantastic. 
When I run it by using this git, it returns probability. 
How can I make it return something similar like your website scanner ? Or specifically, what threshold should I take to say a video is fake or not ? 
I uploaded a fake video that I created. Scanner predicted it right (deepfake detected). But when I run by command, it returns about 0.3 as probability. I'm a little confused here.
Thanks!

**Comment by omer-ze** [comment]
Hi,
 
Thanks for your feedback,

We are using multiple models for video scanning on deepware.ai and decide the final result accordingly. In public repo, only single model works. Therefore, you may see differences in results. If you share us the link of video result page that you scanned on deepware.ai, we can make more detailed analyzes, then feedback to you.
